networks:
  region-a-net:
    name: region-a-net
    driver: bridge

services:
  consul-a:
    image: hashicorp/consul:1.19
    container_name: consul-a
    command: agent -dev -client=0.0.0.0 -ui
    networks:
      - region-a-net
    ports:
      - "8500:8500"

  patroni-a1:
    build:
      context: ../docker/patroni
    container_name: patroni-a1
    hostname: patroni-a1
    networks:
      - region-a-net
    depends_on:
      - consul-a
    volumes:
      - patroni_a1_data:/data/patroni
      - ./patroni-a1.yml:/patroni.yml:ro
    ports:
      - "5501:5432"
      - "8008:8008"

  patroni-a2:
    build:
      context: ../docker/patroni
    container_name: patroni-a2
    hostname: patroni-a2
    networks:
      - region-a-net
    depends_on:
      - consul-a
    volumes:
      - patroni_a2_data:/data/patroni
      - ./patroni-a2.yml:/patroni.yml:ro
    ports:
      - "5502:5432"
      - "8009:8008"

volumes:
  patroni_a1_data:
  patroni_a2_data:
