networks:
  dr-net:
    external: true

services:
  consul-a:
    image: hashicorp/consul:1.19
    container_name: consul-a
    hostname: consul-a
    entrypoint: ["sh", "-c"]
    command:
      - |
        MY_IP=$$(hostname -i)
        exec consul agent -dev \
          -client=0.0.0.0 \
          -ui \
          -datacenter=dc-a \
          -node=consul-a \
          -advertise-wan=$$MY_IP \
          -serf-wan-bind=$$MY_IP \
          -retry-join-wan=consul-b
    networks:
      - dr-net
    ports:
      - "8500:8500"

  patroni-a1:
    build:
      context: ../docker/patroni
    container_name: patroni-a1
    hostname: patroni-a1
    networks:
      - dr-net
    depends_on:
      - consul-a
    volumes:
      - patroni_a1_data:/data/patroni
      - ./patroni-a1.yml:/patroni.yml:ro
    ports:
      - "5501:5432"
      - "8008:8008"

  patroni-a2:
    build:
      context: ../docker/patroni
    container_name: patroni-a2
    hostname: patroni-a2
    networks:
      - dr-net
    depends_on:
      - consul-a
    volumes:
      - patroni_a2_data:/data/patroni
      - ./patroni-a2.yml:/patroni.yml:ro
    ports:
      - "5502:5432"
      - "8009:8008"

volumes:
  patroni_a1_data:
  patroni_a2_data:
